blank_issues_enabled: false
contact_links:
  - name: AzeriteUI5 for Dragonflight Support
    url: https://github.com/GoldpawsStuff/AzeriteUI5/issues
    about: Please report bugs and feature requests here.